#!/bin/sh
# To call this script:
# wget -q https://raw.github.com/gmoon/cloudbees-mongo/master/use-mongo
# MONGO_VERSION=2.4.4 . ./use-mongo
if [[ -z $MONGO_VERSION ]]; then
   echo "You must set the MONGO_VERSION environment variable. See http://docs.mongodb.org/manual/tutorial/install-mongodb-on-linux/"
fi

set -e

mkdir -p /scratch/jenkins/mongo
ARCH=`uname -m`

mongo_name=mongodb-linux-${ARCH}-${MONGO_VERSION}

test -f /scratch/jenkins/mongo/${mongo_name}.tgz ||  wget -q -P /scratch/jenkins/mongo http://downloads.mongodb.org/linux/${mongo_name}.tgz

test -f /scratch/jenkins/mongo/${mongo_name}/bin/mongo || tar xzf /scratch/jenkins/mongo/${mongo_name}.tgz  -C /scratch/jenkins/mongo

export PATH=/scratch/jenkins/mongo/${mongo_name}/bin:$PATH

# start mongod
mkdir -p /scratch/jenkins/db
mongod  --smallfiles --dbpath /scratch/jenkins/db --fork

